### ISSUE TITLE
How to send current login User-ID to PostgreSQL

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#1545]
The instructions in:
https://docs.lizmap.com/current/en/publish/advanced_lizmap_config.html#examples
don't work for me. I added a file named form_variables.js to media/js/default with the content from the link above does not insert 
however, I do not know how to activate this for a specific table/field.
Simply adding
rilevatore: 'lizmap_user_login'
where rilevatore is the name of the field of one table does not work.
What else is necessary?

**Comment by pcav** [comment]
from the log:
'rilevatore' => '',

**Comment by pcav** [comment]
A related question, perhaps worth a separate ticket: 
would the variable 'login' or 'lizmap_user_login' be available for other tasks, e.g. adding to the print layout? If so, with which syntax?

**Comment by josemvm** [comment]
@pcav try `login: 'rilevatore'` instead of `rilevatore: 'lizmap_user_login'`

**Comment by pcav** [comment]
Thanks. Is this the correct syntax? If so, IMHO the documentation could be improved.

**Comment by josemvm** [comment]
done https://github.com/3liz/lizmap-documentation/pull/156

**Comment by josemvm** [comment]
here https://github.com/3liz/lizmap-documentation/pull/157

**Comment by pcav** [comment]
Thanks a lot.
Any news about the availability of lizmap variables in other context, e.g. printing?
Cheers

**Comment by josemvm** [comment]
@pcav 
> Any news about the availability of lizmap variables in other context, e.g. printing?

i have no idea about it...

> perhaps worth a separate ticket

i think so too

can we close this issue?

thanks

**Comment by pcav** [comment]
It still does not work with me. How do I specify which table and filed the login variable should be inserted into?

**Comment by josemvm** [comment]
> How do I specify which table and filed the login variable should be inserted into?

it is not necessary to specify any table, just the field name, e.g. : `login: 'login'`

**Comment by rmarzocchi84** [comment]
I have no idea about printing (never tested) but reading your question the first thing iI noticed is: 

> I added a file named form_variables.js to media/js/default

Normally  I use `media/js/name_of_project` 

I think more information are also available on this issue: 

https://github.com/3liz/lizmap-web-client/issues/624

**Comment by rmarzocchi84** [comment]
In this script I think you need to use the name of postgreSQL field using login, but perhaps @mdouchin (the author of the original script) has more detail  

```
var formPrefix = 'jforms_view_edition';

// Name of the QGIS vector layer fields which must containt the user info
var userFields = {
    login: 'login',
    firstname: 'lizmap_user_firstname',
    lastname: 'lizmap_user_lastname',
    organization: 'lizmap_user_organization'
};


lizMap.events.on({

    'lizmapeditionformdisplayed': function(e){

        // If user is logged in
        if( $('#info-user-login').length ){
            // Loop through the needed fields
            for( var f in userFields ){
                // If the user has some data for this property
                if( $('#info-user-' + f).text() ){
                    // If the field exists in the form
                    var fi = $('#' + formPrefix + '_' + userFields[f]);
                    if( fi.length ){
                        // Set val from lizmap user data
                        fi.val( $('#info-user-' + f).text() )
                        // Set disabled
                     // fi.attr('disabled', 'disabled');
						fi.hide();
                    }
                }
            }
        }

    }

});
```

I also use the login js variable in an external web page, but not in print:

```
lizMap.events.on({
	uicreated: function(e) {


		if( $('#info-user-login').length ){
            // Loop through the needed fields
			for( var f in userFields ){
				var fi = $('#' + userFields[f]);
                if (f=='login'){
					var user = $('#info-user-' + f).text()
					//window.alert(user);
				}
            }
        }


		/*var mediaLink = OpenLayers.Util.urlAppend(
		lizUrls.media,
		OpenLayers.Util.getParameterString(lizUrls.params)
		);*/

		//var frameSrc = mediaLink +'&path=../../../../../../query/eventop.php';
		lizMap.addDock(
		'eventop', // nome dock
		'Nuovo evento puntuale', // titolo
		'right-dock', //contenuto
		//frameSrc,
		'<iframe width="100%" height="650"  src="../../../../../../query/eventop.php?login='+user+'" frameborder="0" allowfullscreen overflow-y:scroll ></iframe>',
		'icon-large icon-map-marker'
		);


}
});
```

**Comment by pcav** [comment]
Thanks, now it works.
