### ISSUE TITLE
Problem with filter data by group using virtual fields or group 

### ISSUE THREAD

**Issue by rmarzocchi84** [3liz/lizmap-web-client#1912]
I encountered two problem with filter data by group. 

1. virtual field doesn't work 

2. if layer is part of a group filter doesn't work 

Tested with LWC 3.3.11 and QGIS 3,10.11

Here a project affected by problem https://www.gishosting.gter.it/lizmap-web-client/lizmap/www/index.php/view/map/?repository=workshop&project=test_filter

Here the plugin options selected: 
![image](https://user-images.githubusercontent.com/4061154/98008951-57132e80-1df5-11eb-9cd4-91a31f6a7011.png)

Here the attribute table of my layers:
![image](https://user-images.githubusercontent.com/4061154/98009134-80cc5580-1df5-11eb-8e4e-14d30580753b.png)

The layer affected by the problem is a postgis table

**Comment by rldhont** [comment]
Hi @rmarzocchi84,

The point 2. has been fixed in Lizmap-Web-Client 3.4 with Lizmap-Plugin as a QGIS Server plugin.

The point 1. is dependant on QGIS Server capabilities. I don't know if QGIS Server can filter layers based on  virtual field. I invite you to test Lizmap Web Client 3.4 beta 1 with Lizmap-plugin installed as a QGIS Server plugin and give us some feedback.

**Comment by rldhont** [comment]
Linked to lizmap-plugin https://github.com/3liz/lizmap-plugin/pull/324 and QGIS Server https://github.com/qgis/QGIS/pull/40556 https://github.com/qgis/QGIS/pull/40585 https://github.com/qgis/QGIS/pull/40584

**Comment by Gustry** [comment]
Is this not fixed by upstream new releases ? (QGIS Server and Lizmap QGIS Server)

**Comment by Gustry** [comment]
Please check the latest comment : https://github.com/3liz/lizmap-web-client/issues/1912#issuecomment-760624837
The bot is confused on this ticket.

**Comment by relume** [comment]
On `QGIS Server 3.35.0-Master nightly build (Unbuntu Lunar)` virtual fields (on GeoPackage Layers - I do not know for other layer types) can still not be filtered on WMS service (GetFeatureInfo). But existing virtual fields are served like other static fields in the features attributes result (if requested without filter or with a filter on an static field). Thus filter expressions like:

does return the filtered features items as expected
`… FILTER=myLayer:"myFieldStatic"='xxx' ...`

does not return any features
`… FILTER=myLayer:"myFieldVirtual"='xxx' ...`

with the condition that `myFieldStatic` and `myFieldVirtual` do hold the very same values (e.g):

```
myFieldStatic = lower('myFieldSource') calculated static

myFieldVirtual = lower('myFieldSource') calculated dynamically as virtual field

```
